name: Run Tests

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -rf package-lock.json node_modules
          npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test -- --run

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports